def COLOR_MAP = [
    'SUCCESS' : 'good',
    'FAILURE' : 'danger',
    'UNSTABLE': 'warning'
]

pipeline {   
    agent any

    tools {
        jdk "JDK21"
        maven "Maven3.9"
    }

    environment {
        NEXUS_VERSION       = "nexus3"
        NEXUSIP             = "nexus.eprofile.in"
        NEXUSPORT           = "8081"
        NEXUS_REPOSITORY    = "vprofile-repo"
        NEXUS_CREDENTIAL_ID = "nexuslogin" 
        ARTVERSION          = "${env.BUILD_ID}"
        
        SONARSERVER         = "sonarserver" 
        SONARSCANNER        = "sonarscanner" 
        
        TOMCAT_IP           = "app01.eprofile.in"
        TOMCAT_USER         = "ubuntu"
    }

    stages {
        stage("Test") {
            steps {
                sh "mvn test"
            }
        }

        stage("OWASP Dependency Check") {
                    steps {
                        withCredentials([string(credentialsId: 'nvd-api-key', variable: 'NVD_API_KEY')]) {
                                sh "mvn dependency-check:check -DnvdApiKey=\$NVD_API_KEY -DnvdApiDelay=10000 -DfailOnError=false || true"                        }
                    }
                    post {
                        always {
                            dependencyCheckPublisher pattern: 'target/dependency-check-report.xml',
                                stopBuild: false  

                        }
                    }
                }
        stage('Sonar Analysis') {
            environment {
                scannerHome = tool "${SONARSCANNER}"
            }
            steps {
               withSonarQubeEnv("${SONARSERVER}") {
                   sh '''${scannerHome}/bin/sonar-scanner \
                   -Dsonar.projectKey=vprofile \
                   -Dsonar.projectName=vprofile \
                   -Dsonar.projectVersion=1.0 \
                   -Dsonar.sources=src/ \
                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                   -Dsonar.junit.reportsPath=target/surefire-reports/ \
                   -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
              }
            }
        }

        stage("Quality Gate") {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage("Package & Archive Artifacts") {
            steps {
                sh "mvn -DskipTests package"
            }
            post {
                success {
                    echo "Archiving Artifacts .." 
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }


        stage('Deploy to Tomcat') {
            steps {
                sshagent(['tomcat-ssh-key']) {
                    sh """
                    scp -o StrictHostKeyChecking=no target/vprofile-v2.war ${TOMCAT_USER}@${TOMCAT_IP}:/tmp/vprofile-v2.war
                    
                    ssh -o StrictHostKeyChecking=no ${TOMCAT_USER}@${TOMCAT_IP} '
                        sudo systemctl stop tomcat9 || true
                        sudo rm -rf /var/lib/tomcat9/webapps/ROOT*
                        sudo cp /tmp/vprofile-v2.war /var/lib/tomcat9/webapps/ROOT.war
                        sudo chown tomcat:tomcat /var/lib/tomcat9/webapps/ROOT.war
                        sudo systemctl start tomcat9
                    '
                    """
                }
            }
        }
    }

    post {
        always {
            echo 'Sending Slack Notifications...'
            slackSend channel: '#jenkins-cicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}
