version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      
  pre_build:
    commands:
      - echo "Fetching CodeArtifact Token..."
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain vprofile-domain --query authorizationToken --output text`
      - export CODEARTIFACT_URL=`aws codeartifact get-repository-endpoint --domain vprofile-domain --repository vprofile-repo --format maven --query repositoryEndpoint --output text`
      
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Compiling and Packaging Java code..."
      - mvn -s settings.xml clean package -DskipTests
      
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Renaming artifact for Beanstalk Tomcat..."
      - mv target/vprofile-v2.war target/ROOT.war

artifacts:
  files:
    - target/ROOT.war
  discard-paths: yes