version: 0.2
env:
  parameter-store:
    LOGIN: /strata-ops/sonar-token
    Organization: /strata-ops/sonar-org
    Project: /strata-ops/sonar-project

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - apt-get update
      - apt-get install -y jq checkstyle wget curl
      
      - echo "Installing tfsec..."
      - wget -qO- https://github.com/aquasecurity/tfsec/releases/download/v1.28.1/tfsec-linux-amd64 > /usr/local/bin/tfsec
      - chmod +x /usr/local/bin/tfsec
      
      - echo "Installing TruffleHog..."
      - curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
      
  pre_build:
    commands:
      - echo "Fetching CodeArtifact Token for tests..."
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain vprofile-domain --query authorizationToken --output text`
      - export CODEARTIFACT_URL=`aws codeartifact get-repository-endpoint --domain vprofile-domain --repository vprofile-repo --format maven --query repositoryEndpoint --output text`
      
  build:
    commands:
      - echo "1. Running TruffleHog (Secrets Scanning)..."
      - trufflehog filesystem . --only-verified --fail
      
      - echo "2. Running tfsec (IaC Security Scanning)..."
      - tfsec ./03-aws-cloud-native/terraform --soft-fail
      
      - echo "3. Running Tests and SonarCloud (SAST) Analysis..."
      - mvn -s settings.xml test checkstyle:checkstyle sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      
      - sleep 5
      - echo "Checking SonarCloud Quality Gate..."
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project > result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then echo "Quality Gate Failed!"; exit 1 ;fi