## This file defines AWS SSM Parameters for storing sensitive information such as SonarQube token and Nexus password. 
## The parameters are stored as SecureString to ensure they are encrypted at rest. 
## The lifecycle block is used to ignore changes to the value, allowing you to update the parameters manually without Terraform trying to revert them back to "pending".


# ==========================================
# 1. (Late Binding)
# ==========================================

resource "aws_ssm_parameter" "nexus_password" {
  name  = "/strata-ops/nexus-password"
  type  = "SecureString"
  value = "pending"
  lifecycle { ignore_changes = [value] }
}

resource "aws_ssm_parameter" "tomcat_private_key" {
  name = "/strata-ops/tomcat-ssh-key"
  type = "SecureString"

  value = file("${path.module}/ec2-eprofile-key")
}

# ==========================================
# 2. (Generated by Terraform)
# ==========================================

resource "random_password" "jenkins_admin" {
  length  = 8
  special = false
}
resource "aws_ssm_parameter" "jenkins_password" {
  name  = "/strata-ops/jenkins-admin-password"
  type  = "SecureString"
  value = random_password.jenkins_admin.result
}

resource "random_password" "db_password" {
  length  = 8
  special = false
}
resource "aws_ssm_parameter" "mysql_password" {
  name  = "/strata-ops/mysql-password"
  type  = "SecureString"
  value = random_password.db_password.result
}

# ==========================================
# 3. (External APIs)
# ==========================================

resource "aws_ssm_parameter" "github_key" {
  name  = "/strata-ops/github-private-key"
  type  = "SecureString"
  value = file("${path.module}/aws-2-github")
  lifecycle { ignore_changes = [value] }
}

resource "aws_ssm_parameter" "sonar_token" {
  name  = "/strata-ops/sonar-token"
  type  = "SecureString"
  value = "pending" # ← غيرها لـ pending زي nexus
  lifecycle { ignore_changes = [value] }
}

resource "aws_ssm_parameter" "slack_token" {
  name  = "/strata-ops/slack-token"
  type  = "SecureString"
  value = "YfMi7uwL9nrgbCUn0kP9wJgC" # ← حط التوكن هنا
  lifecycle { ignore_changes = [value] }
}