apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual ## same as the storageClassName defined in the PV
  resources:
    requests:
      storage: 2Gi