---
- name: Install and Start Minikube on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Update apt and install dependencies
      apt:
        name: [curl, wget, apt-transport-https, conntrack]
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Download Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Download kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Start Minikube
      become: false
      command: minikube start --driver=docker
      register: start_out

    - debug:
        msg: "{{ start_out.stdout }}"