Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  end

  ### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/stream9"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    db01.vm.provision "shell", path: "mysql.sh"
  end

  ### Memcache vm  ####
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "centos/stream9"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    end
    mc01.vm.provision "shell", path: "memcache.sh"
  end

  ### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "centos/stream9"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.16"
    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    end
    rmq01.vm.provision "shell", path: "rabbitmq.sh"
  end

  ### tomcat vm (App) ###
  config.vm.define "app01" do |app01|
    app01.vm.box = "ubuntu/jammy64"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
    
    app01.vm.synced_folder "../../", "/vagrant"

    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2        
    end
    app01.vm.provision "shell", path: "tomcat_ubuntu.sh"
  end

  ### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"
    web01.vm.provider "virtualbox" do |vb|
      vb.gui = false 
      vb.memory = "512" 
    end
    web01.vm.provision "shell", path: "nginx.sh"
  end

end