apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp ## The name of the deployment that will be used to base the connection string for the application to connect to the Tomcat server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp-pod ## The selector that will be used to match the deployment to the service of the application
  template:
    metadata:
      labels:
        app: vproapp-pod ## The label that will be used to match the deployment to the service of the application
    spec:
      containers:
      - name: vproapp-container
        image: amrmamer/vprofileapp
        ports:
        - containerPort: 8080

        resources:
          requests:
            memory: "512Mi"   
            cpu: "250m"     
          limits:
            memory: "1Gi"     
            cpu: "500m"    

        env:
        - name: RABBITMQ_HOSTNAME
          value: vprormq-service

        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: mq-secrets
              key: username

        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: mq-secrets
              key: password


        - name: MEMCACHED_HOSTNAME
          value: vprocache-service


        - name: RDS_HOSTNAME
          value: vprodb-service 

        - name: RDS_USERNAME
          valueFrom:
            secretKeyRef:
              name: rds-secrets
              key: username

        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-secrets
              key: password

      initContainers:
        - name: wait-for-services
          image: busybox:1.28
          command: ['sh', '-c', "until nc -zvw1 vprordb-service 3306 && nc -zvw1 vprormq-service 5672 && nc -zvw1 vprocache-service 11211; do echo 'Waiting for backend...'; sleep 2; done;"]              