# ====== Application Variables (Production Version) ======
app:
  image: "amrmamer/vprofileapp"
  tag: "latest"
  replicaCount: 2
  serviceName: "vproapp-service"
  
  externalSecrets:
    enabled: true
    secretName: "vpro-app-secrets"