# ====== Application Variables ======

# 1. (Application)
app:
  image: "amrmamer/vprofileapp"
  tag: "latest"
  replicaCount: 1
  serviceName: "app-tomcat-service"

# 2. (MySQL)
db:
  image: "amrmamer/vprofiledb"
  tag: "latest"
  rootPassword: "vprodbpass"
  username: "vprodb"
  password: "vprodbpass"
  storage: "2Gi"
  serviceName: "vprodb-service"

# 3. (RabbitMQ)
rmq:
  image: "rabbitmq"
  tag: "3-management"
  replicaCount: 1
  username: "guest"
  password: "guest"
  serviceName: "vprormq-service"

# 4. (Memcached)
memcached:
  image: "memcached"
  tag: "latest"
  replicaCount: 1
  serviceName: "vprocache-service"