# ====== Application Variables (Production Version) ======
app:
  image: "" ## The image will be set dynamically in the GitHub Actions workflow during deployment
  tag: "" ## The tag will be set dynamically in the GitHub Actions workflow during deployment
  replicaCount: 2
  serviceName: "vproapp-service"
  
  externalSecrets:
    enabled: true
    secretName: "vpro-app-secrets"