jenkins:
  systemMessage: "Welcome to Strata-Ops Enterprise Jenkins - Automated by Terraform & JCasC"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  numExecutors: 2
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "Amr"
        name: "Amr"
        password: "${ADMIN_PASSWORD}" 
        properties:
        - mailer:
            emailAddress: "amr@gmail.com"

# ----------------- Credentials -----------------
credentials:
  system:
    domainCredentials:
    - credentials:
      # 1. Nexus Credentials
      - usernamePassword:
          id: "nexuslogin"
          scope: GLOBAL
          username: "admin"
          password: "${NEXUS_PASSWORD}"
          description: "Nexus Authentication"
          

      # 4. GitHub SSH Key
      - basicSSHUserPrivateKey:
          id: "github-ssh-key"
          scope: GLOBAL
          username: "git"
          privateKeySource:
            directEntry:
              privateKey: "${GITHUB_PRIVATE_KEY}"
          description: "GitHub Private Key for cloning repo"

      # 5. Tomcat EC2 SSH Key
      - basicSSHUserPrivateKey:
          id: "tomcat-ssh-key"
          scope: GLOBAL
          username: "ubuntu"
          privateKeySource:
            directEntry:
              privateKey: "${TOMCAT_SSH_KEY}"
          description: "SSH Key to deploy to Tomcat EC2"

# ----------------- Tools Setup -----------------
tool:
  git:
    installations:
    - name: "Default"
      home: "git"
  jdk:
    installations:
    - name: "JDK21"
      home: "/usr/lib/jvm/java-21-openjdk-amd64" 
  maven:
    installations:
    - name: "Maven3.9"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.9.9"
  sonarRunnerInstallation:
    installations:
    - name: "sonarscanner"
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "4.7.0.2747"

# ----------------- Integrations -----------------
unclassified:
  location:
    url: "http://jenkins.eprofile.in/"
  slackNotifier:
    botUser: false
    room: "#jenkins-cicd"
    sendAsText: false
    teamDomain: "devops-m8f7836"
    tokenCredentialId: "Slack-token"
  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations:
    - name: "sonarserver"
      serverUrl: "http://sonarqube.eprofile.in:80"
      credentialsId: "sonertoken"
      triggers:
        skipScmCause: false
        skipUpstreamCause: false

## ----------------- Jobs Setup -----------------

jobs:
  - script: >
      pipelineJob('Strata-Ops-Phase2-Pipeline') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote { 
                              url('https://github.com/amramer101/Strata-Ops.git') 
                              credentials('github-ssh-key')
                          }
                          branches('main')
                      }
                  }
                  scriptPath('02-aws-lift-shift/Jenkinsfile')
              }
          }
      }