apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vpro-app-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ssm-store
    kind: SecretStore
  target:
    name: vpro-app-secrets ## The name of the Kubernetes Secret that will be created
    creationPolicy: Owner
  data:
    # 1. (RDS)
    - secretKey: db_host 
      remoteRef:
        key: /strata/rds_endpoint
    
    - secretKey: db_password
      remoteRef:
        key: /strata/rds_password

    - secretKey: db_username
      remoteRef:
        key: /strata/rds_username        

    # 2. (Amazon MQ / RabbitMQ)
    - secretKey: rmq_host
      remoteRef:
        key: /strata/rmq_endpoint

    - secretKey: rmq_user
      remoteRef:
        key: /strata/rmq_username

    - secretKey: rmq_password
      remoteRef:
        key: /strata/rmq_password

    # 3. (ElastiCache / Memcached)
    - secretKey: cache_host
      remoteRef:
        key: /strata/memcached_endpoint