apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp-deployment
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: vproapp-pod
  template:
    metadata:
      labels:
        app: vproapp-pod
    spec:
      # دي الكونتينرز الأساسية
      containers:
      - name: vproapp-container
        image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
        ports:
        - containerPort: 8080
        env:
        # --- MySQL (RDS) ---
        - name: RDS_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: db_host
        - name: RDS_USERNAME
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: db_username
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: db_password
        # --- RabbitMQ (Amazon MQ) ---
        - name: RABBITMQ_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: rmq_host
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: rmq_user
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: rmq_password
        # --- Memcached (ElastiCache) ---
        - name: MEMCACHED_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: cache_host
    
      initContainers:
      - name: wait-for-services
        image: busybox:1.28
        env:
        - name: RDS_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: db_host
        - name: RABBITMQ_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: rmq_host
        - name: MEMCACHED_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: cache_host      
        command:
        - "sh"
        - "-c"
        - >
          echo "RDS: $RDS_HOSTNAME";
          echo "RMQ: $RABBITMQ_HOSTNAME";
          echo "MEM: $MEMCACHED_HOSTNAME";
          RMQ_CLEAN=$(echo $RABBITMQ_HOSTNAME | cut -d/ -f3 | cut -d: -f1);
          echo "Cleaned RMQ: $RMQ_CLEAN";
          until nc -zvw1 $RDS_HOSTNAME 3306 && nc -zvw1 $RMQ_CLEAN 5671 && nc -zvw1 $MEMCACHED_HOSTNAME 11211; do
            echo 'Waiting for external services...';
            sleep 2;
          done;