apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp-deployment
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: vproapp-pod
  template:
    metadata:
      labels:
        app: vproapp-pod
    spec:
      containers:
      - name: vproapp-container
        image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
        ports:
        - containerPort: 8080

        env:
        # --- MySQL (RDS) ---
        - name: RDS_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets # نفس الاسم اللي في الـ ExternalSecret
              key: db_host
        - name: RDS_USERNAME
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: db_username
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: db_password

        # --- RabbitMQ (Amazon MQ) ---
        - name: RABBITMQ_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: rmq_host
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: rmq_user
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: rmq_password

        # --- Memcached (ElastiCache) ---
        - name: MEMCACHED_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: vpro-app-secrets
              key: cache_host

      initContainers:
        - name: wait-for-services
          image: busybox:1.28
          command: ['sh', '-c', "until nc -zvw1 $RDS_HOSTNAME 3306 && nc -zvw1 $RABBITMQ_HOSTNAME 5672; do echo 'Waiting for external services...'; sleep 2; done;"]