apiVersion: v1
kind: Service
metadata:
  name: vprocache-service ## The name of the service that will be used to base the connection string for the application to connect to the Memcached server
spec:
  ports:
    - port: 11211
      targetPort: 11211
  selector:
    app: vprocache-pod ## The selector that will be used to match the service to the deployment of the Memcached server