apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vprofile-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: vprofile.local.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-tomcat ## The name of the service that will be used to route traffic to the application 
            port:
              number: 8080