name: CI/CD Pipeline for EKS

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/6.1-EKS-CICD.yml'
      - '6.1-EKS-Provisioning-with-Push-Based-CICD/eprofile-chart/**'
      - 'Dockerfile'
  workflow_dispatch: ## Allows manual triggering from GitHub Actions UI

env:
  AWS_REGION: eu-central-1
  ROLE_TO_ASSUME: arn:aws:iam::279064251683:role/GitHubActions-EKS-Role ## Update with the ARN of the IAM Role created for GitHub Actions
  ECR_REPOSITORY: eks_dockertomcat_repo_staraops              
  EKS_CLUSTER_NAME: strata-eks-cluster 
  HELM_CHART_PATH: 6.1-EKS-Provisioning-with-Push-Based-CICD/eprofile-chart

permissions:
  contents: read
  security-events: write
  id-token: write ## Required for OIDC authentication

jobs:

  # ----------------------- JOB 1 - Scan Source Code With Checkov and Kube-Score  ------------------------
  security-scan:
      name: Infrastructure & Manifest Security Scan
      runs-on: ubuntu-latest
      
      ## For Terraform and Helm security scanning, we will use Checkov. For Kubernetes manifest scanning, we will use Kube-score.
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Run Checkov for Terraform & Helm
          uses: bridgecrewio/checkov-action@master
          with:
            directory: 6.1-EKS-Provisioning-with-Push-Based-CICD/
            framework: terraform,helm
            soft_fail: true 
            output_format: cli

        - name: Install Kube-score
          run: |
            wget https://github.com/zegl/kube-score/releases/download/v1.17.0/kube-score_1.17.0_linux_amd64 -O kube-score
            chmod +x kube-score
            sudo mv kube-score /usr/local/bin/

        - name: Run Kube-score on Helm Templates
          run: |
            helm template 6.1-EKS-Provisioning-with-Push-Based-CICD/eprofile-chart/ | kube-score score - || true ## Continue even if kube-score finds issues, we will report them in the next step

# --------------------- JOB 2 - Build, Scan & Push to ECR -------------------------

  build-scan-push:
    name: Docker Build, Scan and Push
    runs-on: ubuntu-latest
    needs: security-scan

    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} 
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }} .

      - name: Trivy - Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          format: sarif
          output: trivy-image-results.sarif
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Upload Image Scan Results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-image-results.sarif
          category: trivy-image

      - name: Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} 
        run: |
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}


# --------------------- JOB 3 - Deploy to EKS via Helm -------------------------
  deploy-to-eks:
    name: Helm Deploy to EKS
    runs-on: ubuntu-latest
    needs: build-scan-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update KubeConfig
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.0

      - name: Deploy Application with Helm
        run: |
            helm upgrade --install vproapp ${{ env.HELM_CHART_PATH }} \
              --namespace default \
              --set app.image=${{ needs.build-scan-push.outputs.registry }}/${{ env.ECR_REPOSITORY }} \
              --set app.tag=${{ github.sha }} \
              --wait --timeout 5m